### ISSUE TITLE
Fix the quotes at the end

### ISSUE THREAD

**Issue by aric87** [devinhuizingh/freezer-inventory#6]
I'm not sure what the purpose of the `"'"` is at the end of the string. It seems odd for a URL to need to end with a single quote. 
https://github.com/devinhuizingh/freezer-inventory/blob/master/public/js/script.js#L124

**Comment by devinhuizingh** [comment]
the whole url needs to be a string, but I have a variable in there, so I need to seperate

**Comment by devinhuizingh** [comment]
forget that comment :-)   quote is gone
